name:                pso-ageframe
version:             0.1.0.0
synopsis:            Initial project template from stack
description:         Please see README.md
homepage:            https://github.com/dktn/pso-ageframe#readme
license:             MIT
author:              Adam Szlachta
maintainer:          adam.szlachta@gmail.com
copyright:           Apache 2.0
ghc-options:         -Wall

dependencies:
  - base >= 4.7 && < 5
  - vector
  - mwc-random
  - primitive

  - deepseq
  - text
  - containers
  # - directory
  - filepath
  # - unordered-containers
  - yaml
  - criterion

library:
  source-dirs:        src

default-extensions:
  - OverloadedStrings
  # - NoMonomorphismRestriction
  - DeriveGeneric

executables:
  pso-ageframe-exe:
    main:             Main.hs
    source-dirs:      app
    dependencies:
      - pso-ageframe
      - ekg
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -with-rtsopts=-T
  pso-ageframe-bench:
    main:             Benchmark.hs
    source-dirs:      bench
    dependencies:
      - pso-ageframe
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -with-rtsopts=-T

tests:
  pso-ageframe-test:
    # cpp-options: -DTEST
    main: Main.hs
    source-dirs:
      - test
      - src
    dependencies:
      - pso-ageframe
      - tasty
      - tasty-quickcheck
      - tasty-smallcheck
      - tasty-hunit
      # - hspec == 2.*
      # - QuickCheck
      # - temporary
      # - mockery >= 0.3
      # - interpolate
      # - aeson-qq
      # - aeson >= 0.10
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
