name:                framework
version:             0.1.0.0
synopsis:            Initial project template from stack
description:         Please see README.md
homepage:            https://github.com/dktn/framework#readme
license:             MIT
author:              Adam Szlachta
maintainer:          adam.szlachta@gmail.com
copyright:           Apache 2.0
ghc-options:         -Wall

dependencies:
  - base >= 4.7 && < 5
  - deepseq
  # - directory
  - filepath
  - text
  - containers
  # - unordered-containers
  - yaml
  - criterion

library:
  source-dirs:        src

default-extensions:
  - OverloadedStrings
  - NoMonomorphismRestriction
  - DeriveGeneric

executables:
  framework-exe:
    main:             Main.hs
    source-dirs:      app
    dependencies:
      - framework
      - ekg
    ghc-options:      -threaded -rtsopts -with-rtsopts=-N -with-rtsopts=-T
  framework-bench:
    main:             Benchmark.hs
    source-dirs:      bench
    dependencies:
      - framework
    ghc-options:      -threaded -rtsopts -with-rtsopts=-N -with-rtsopts=-T

tests:
  framework-test:
    # cpp-options: -DTEST
    main: Tests.hs
    source-dirs:
      - test
      - src
    dependencies:
      - framework
      - tasty
      - tasty-quickcheck
      - tasty-smallcheck
      - tasty-hunit
      # - hspec == 2.*
      # - QuickCheck
      # - temporary
      # - mockery >= 0.3
      # - interpolate
      # - aeson-qq
      # - aeson >= 0.10
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
